// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlResponseData } from "./ControlResponseData";

export type ControlResponse = {
    /**
     * Sequence number of the request this response corresponds to
     */
    seq: number;
    /**
     * Indicates whether the request was successful
     */
    success: boolean;
    /**
     * Error message if success is false
     */
    message: string | null;
    /**
     * Optional response data for successful requests
     */
    data: ControlResponseData | null;
};
