// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortReserved } from "./PortReserved";

export type ControlResponseData = { "Initialize": { version: string, } } | { "AllocatePorts": { ports: Array<PortReserved>, } } | { "StartGdbServer": { pid: number, } } | { "StreamStatus": { stream_id: number, status: string, } } | "Heartbeat";
