// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortSet } from "./PortSet";

export type PortAllocatorSpec = { 
/**
 * List of all allocated port sets 
 */
all_ports: Array<PortSet>, };
