// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * These ports are allocated as a group, consecutively 
 */
export type PortSet = { 
/**
 * Use it as starting port if possible. 0 means any available port, but still consecutive 
 */
start_port: number, 
/**
 * List of id strings to identify this port. Should be unique across the entire session 
 */
port_ids: Array<string>, };
