// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PortReserved = {
    /**
     * Actual port number of server
     */
    port: number;
    /**
     * The stream-id used to connect to this port
     */
    stream_id: number;
    /**
     * String representation of the stream-id, as specified by the client
     */
    stream_id_str: string;
};
