// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Responses are different from events as they represent the result of a request, while events are
 * notifications from the server
 * */
export type ProxyServerEvents = { "event": "GdbServerLaunched", "params": { pid: number, port: number, } } | { "event": "GdbServerExited", "params": { pid: number, exit_code: number, } } | { "event": "StreamStarted", "params": { stream_id: number, port: number, } } | { "event": "StreamClosed", "params": { stream_id: number, } };
