const assert = require("node:assert/strict");
const fs = require("node:fs");
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
const until = async fn => { const deadline=Date.now()+5000; while(!fn()){ if(Date.now()>deadline) throw new Error("RTT watch smoke timed out: "+fn); await sleep(10); } };
exports.run = async ({vscode, api, rttConnection, calls, base, instance, sessionId}) => {
    const provider = api.rttWatchProvider;
    await vscode.commands.executeCommand("mcu-ai-debug.rttWatch.copyFirmwarePrompt");
    const prompt=await vscode.env.clipboard.readText();
    assert(prompt.includes("SEGGER_RTT_Write(channel, buffer, length)") && prompt.includes("UART transmit API") && prompt.includes("JSON Lines"));
    assert.equal(Buffer.byteLength(prompt),prompt.length,"Firmware prompt must be English ASCII");
    await until(()=>provider.store.leaves.some(n=>n.scalar===17));
    assert.equal(provider.store.roots.filter(n=>n.children.length).length,1);
    assert.equal(provider.store.source(provider.store.roots[0].id).sessionId,sessionId);
    const before = calls.length;
    const frame = value => 'buzzer_debug='+JSON.stringify({frequency_hz:4000+value, enabled:value%2===0, nested:{gain:value}, list:[value,null], text:'<img src=x onerror="bad()">'})+'\n';
    rttConnection.write(frame(0));
    await until(()=>provider.store.leaves.some(n=>n.path[0]==='frequency_hz'));
    assert.equal(calls.length,before,"RTT variable discovery must not issue GDB reads or start another poller");
    const root=(await provider.getChildren())[0];
    assert.equal(root.readonly,true);
    const watches=await provider.getChildren(root);
    assert(watches.some(n=>n.label==='buzzer_debug'&&n.hasChildren));
    const originalPick=vscode.window.showQuickPick, originalSave=vscode.window.showSaveDialog;
    let destination;
    try {
        vscode.window.showQuickPick=async items=>items.filter(item=>!item.key || /frequency_hz|gain/.test(item.key));
        vscode.window.showSaveDialog=async()=>vscode.Uri.file(destination);
        destination=`${base}/rtt-snapshot-${instance}.json`;
        await vscode.commands.executeCommand('mcu-ai-debug.rttWatch.saveSnapshot');
        const snapshot=JSON.parse(fs.readFileSync(destination,'utf8'));
        assert.equal(snapshot.format,'mcu-ai-debug.json-watch.v1');
        assert(Object.values(snapshot.values).includes(4000));
        assert(Object.values(snapshot.values).includes(true));
        assert(Object.values(snapshot.values).includes(null));
        assert(snapshot.sources.every(s=>s.sessionId===sessionId&&s.channel===0));
        destination=`${base}/rtt-recording-${instance}.jsonl`;
        await vscode.commands.executeCommand('mcu-ai-debug.rttWatch.startRecording');
        assert(provider.recording);
        rttConnection.write(Array.from({length:25},(_,i)=>frame(i+1)).join(''));
        await until(()=>provider.store.leaves.some(n=>n.path[0]==='frequency_hz'&&n.scalar===4025));
        await vscode.commands.executeCommand('mcu-ai-debug.rttWatch.stopRecording');
        const rows=fs.readFileSync(destination,'utf8').trim().split('\n').map(JSON.parse);
        assert.equal(rows.length,25,"Recording must preserve all received samples independently of GUI batching");
        assert.equal(rows[0].source.sessionId,sessionId);
        assert(Object.values(rows[24].values).includes(4025));
        destination=`${base}/rtt-recording-${instance}.csv`;
        await vscode.commands.executeCommand('mcu-ai-debug.rttWatch.startRecording');
        rttConnection.write(frame(26));
        await until(()=>provider.store.leaves.some(n=>n.scalar===4026));
        await vscode.commands.executeCommand('mcu-ai-debug.rttWatch.stopRecording');
        assert(fs.readFileSync(destination,'utf8').includes('"4026"'));
        await vscode.commands.executeCommand('mcu-ai-debug.rttWatch.openGraph');
        assert(provider.grapher.isOpen);
        assert.equal(provider.grapher.getGraphKeys().length,2);
        rttConnection.write(frame(27));
        await until(()=>provider.store.leaves.some(n=>n.scalar===4027));
        assert.equal(calls.length,before);
        assert.equal(api.liveWatchMcpServer.getPort(),null);
        fs.writeFileSync(`${base}/rtt-watch-${instance}.json`,JSON.stringify({typedSnapshot:true,jsonlSamples:rows.length,csv:true,independentGraph:true,extraGdbRequests:0,extraRttPollers:0,hardware:false}));
    } finally {vscode.window.showQuickPick=originalPick;vscode.window.showSaveDialog=originalSave;}
};
